package studentskills.exception;

public enum ErrorCode {
	INVALID_INPUT_ARGUMENT, INVALID_INPUT_PARAMS, INVALID_INPUT_EMPTY, INVALID_PATH, INVALID_IO, INVALID_INPUT_FORMAT,
	EOF, RESOURCE_ALREADY_EXISTS, RESOURCE_NOT_FOUND, RESOURCE_NOT_CLOSED, SECURITY, ARITHMATIC_EXCEPTION,
	CANNOT_MODIFY, CANNOT_UPDATE_OBSERVERS, SKILLS_RANGE_EXCEEDED
}
